In [2]:
# Imports

import pandas as pd

In [15]:
# Read excel file

df = pd.read_excel('data/MOSAIC - Desbloqueado.xlsx', sheet_name='Background')
df = df.drop(0)

# df = df.iloc[:, [0, -3, -2, -1]]
# df.to_csv('Background.csv', index=False)
df

,Wavelength,Scattered Moonlight,Scattered Starlight,Zodiacal Light,Lower Atmosphere,Upper Atmosphere,Airglow/Residual Continuum,Thermal w/ degrad,%thermal vs total no moon,Sky ALL,Sky NO MOON,Sky ALL+Th,Sky NO MOON+Th
1,390,208.842085,6.313042,13.287076,0.000000,1.537032e-13,33.090570,0.000000,0.000000,261.532774,52.690689,261.532774,52.690689
2,390.02,268.728816,8.134738,17.097465,0.000000,1.698825e-13,42.647983,0.000000,0.000000,336.609002,67.880186,336.609002,67.880186
3,390.04,310.398712,9.410466,19.749009,0.000000,1.307825e-13,49.349449,0.000000,0.000000,388.907637,78.508924,388.907637,78.508924
4,390.06,333.188265,10.114381,21.199464,0.000000,2.211168e-13,53.058345,0.000000,0.000000,417.560455,84.372190,417.560455,84.372190
5,390.08,343.079252,10.419344,21.829358,0.000000,1.698825e-13,54.678913,0.000000,0.000000,430.006866,86.927614,430.006866,86.927614
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29594,1884.485,0.620309,0.018831,1.014648,2418.003697,7.326482e-11,4.373846,288.205623,0.118926,2424.031331,2423.411022,2712.236954,2711.616645
29595,1884.6,1.590072,0.047279,2.348454,2004.761372,2.151723e-12,10.124349,288.606678,0.143067,2018.871526,2017.281454,2307.478205,2305.888132
29596,1884.715,2.537832,0.074439,3.515600,1709.335157,1.775172e-12,15.159802,289.008239,0.167242,1730.622829,1728.084997,2019.631068,2017.093236
29597,1884.83,3.100071,0.089765,4.059015,1476.373677,0.000000e+00,17.510710,289.410305,0.193194,1501.133238,1498.033167,1790.543542,1787.443471
29598,1884.945,2.889646,0.082609,3.580848,1007.843128,0.000000e+00,15.453291,289.812876,0.282205,1029.849522,1026.959876,1319.662398,1316.772752